### ISSUE TITLE
Bug for new apps - template$$1.asWrappedLayout is not a function

### ISSUE THREAD

**Issue by jenweber** [ember-cli/ember-octane-blueprint#141]
See #140. Rolling back to v3.0 for htmlbars gets the app running again.

**Comment by chancancode** [comment]
Fixed in https://github.com/ember-cli/ember-cli-htmlbars/commit/a640658a151fe472fb4a3ecc65a8a11ebf2848f1

Sorry about that!

**Comment by Alonski** [comment]
This is still an issue for me:
https://github.com/Alonski/octane-htmlbars-error
